#!/bin/sh

FILES="fracterrain.ml"

LIBS="str.cma unix.cma nums.cma bigarray.cma sdl.cma sdlttf.cma 
      sdlmixer.cma"

OPTLIBS="str.cmxa unix.cmxa nums.cmxa bigarray.cmxa sdl.cmxa sdlttf.cmxa sdlmixer.cmxa"

OCAMLC=ocamlc.opt
OCAMLCP=ocamlcp
OCAMLOPT=ocamlopt.opt

OCAMLSDLLIB=`ocamlfind query sdl`


#$OCAMLC -c -g -I $OCAMLSDLLIB $LIBS $FILES 
$OCAMLOPT -c -I $OCAMLSDLLIB $OPTLIBS $FILES

